kind: Service
apiVersion: v1
metadata:
  name: chatbot-s
  namespace: arrowtown-production
spec:
  selector:
    app: chatbot-s
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 443
      targetPort: 3000
      name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-s
  namespace: arrowtown-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-s
      branch: ${CICD_GIT_BRANCH}
  template:
    metadata:
      labels:
        app: chatbot-s
        branch: ${CICD_GIT_BRANCH}
    spec:
      containers:
        - name: app
          image: xebnisoftware/chatbot:${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 3000
