apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-service
  namespace: arrowtown-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-service
      branch: ${CICD_GIT_BRANCH}
  template:
    metadata:
      labels:
        app: chatbot-service
        branch: ${CICD_GIT_BRANCH}
    spec:
      containers:
        - name: app
          image: xebnisoftware/chatbot:${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 80
            - containerPort: 3000
