version: '3.9'

services:
    app:
        build: .
        command: ["npm", "run", "start"]

    nginx:
        image: nginx:stable-alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./etc/nginx/.htpasswd:/etc/nginx/.htpasswd # 添加这一行
        ports:
            - '80:80'
        depends_on:
            - app
